/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pulselive.coding.task.yasmin.underdown;

import org.junit.Test;
import static org.junit.Assert.*;

public class LeagueTableGeneratorTest {
    @Test public void appHasAGreeting() {
        LeagueTableGenerator classUnderTest = new LeagueTableGenerator();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
