/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pulselive.coding.task.yasmin.underdown;

public class LeagueTableGenerator {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new LeagueTableGenerator().getGreeting());
    }
}
